name: Workflow for Opentofu Apply

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  OpenTofu_Apply:
    runs-on: self-hosted
    strategy:
      matrix:
        directory:
          [
            "Tofu"
          ]

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Exec OpenTofu fmt check
        id: fmt
        working-directory: ${{ matrix.directory }}
        run: tofu fmt -recursive -check
        continue-on-error: true

      - name: Exec OpenTofu init
        id: init
        working-directory: ${{ matrix.directory }}
        run: tofu init

      - name: Exec OpenTofu apply
        id: apply
        working-directory: ${{ matrix.directory }}
        run: tofu apply -auto-approve
