name: "Tofu Apply"
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write
  contents: read

env:
  ROLE_TO_ASSUME: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  AWS_REGION: us-east-1

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/ec2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read tofu version
        id: tofu-version
        run: echo "version=$(cat .tofu-version)" >> "$GITHUB_OUTPUT"

      - name: Setup Opentofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.tofu-version.outputs.version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Tofu Init
        run: tofu init

      - name: Tofu Apply
        run: tofu apply -auto-approve -no-color