name: OpenTofuApply

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  # Terraform (OpenTofu) 実行ディレクトリを指定してください。例: env:
  # WORK_DIR: ./terraform

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  OpenTofu_Apply:
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Exec OpenTofu fmt check
        id: fmt

        run: tofu fmt -recursive -check
        continue-on-error: true

      - name: Exec OpenTofu init
        id: init

        run: tofu init

      - name: Exec OpenTofu apply
        id: apply

        run: tofu apply -auto-approve