name: test

on:
  workflow_dispatch:
  push:
    branches: ["main"]


env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

permissions:  
  id-token: write
  contents: read

jobs:
  test:
    runs-on: self-hosted
    
    steps:
      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
        
      - name: Opentofu Init
        run: tofu init
        working-directory: ${{ github.workspace }}

      - name: Opentofu Plan
        run: tofu plan
        working-directory: ${{ github.workspace }}
      
      - name: Opentofu Apply
        run: tofu apply -auto-approve
        working-directory: ${{ github.workspace }}