name: test

on:
  push:
    branches:
      - main
    paths:
      - "infra"

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

permissions:  
  id-token: write
  contents: read

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Clean Terraform/Tofu workspace
        run: |
          rm -rf .terraform .tofu .terraform.lock.hcl .tofu.lock.hcl

      - name: Opentofu Init
        run: tofu init

      - name: Opentofu Apply
        run: tofu apply -auto-approve
