jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning workspace..."
          rm -rf * .[^.] .??*
      
      - name: Checkout code
        uses: actions/checkout@v4
