name: test

on:
  push:
    branches:
      - "main"

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

permissions:  
  id-token: write
  contents: read

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
        
      - name: Opentofu Init
        run: tofu init
      
      - name: Terraform Apply
        run: tofu apply -auto-approve
