name: Provision t2.micro EC2

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
env:
  AWS_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  provision-ec2:
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: Opentofu Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd tf-example/
          tofu init
          tofu validate
          tofu plan 
          tofu apply -auto-approve
